


--1. CONT20 생성
DROP TABLE CONT20;

CREATE TABLE CONT20
(
    CONTCODE  VARCHAR2(10),
    CONTNAME  VARCHAR2(20),
    CONTDATE VARCHAR2(8),
    PCODE VARCHAR2(2),
    CONTDESC VARCHAR2(300)
)
;

ALTER TABLE CONT20 NOLOGGING;

INSERT /*+ APPEND*/ INTO CONT20
SELECT  LEVEL AS CONTCODE,
        DBMS_RANDOM.STRING('A', 3) AS CONTNAME,
        '2016'||LPAD(ROUND(DBMS_RANDOM.VALUE(1, 3),0), 2,0)||LPAD(ROUND(DBMS_RANDOM.VALUE(1, 28),0), 2,0) AS CONTDATE,
        DBMS_RANDOM.STRING('U', 1) AS PCODE,
        DBMS_RANDOM.STRING('A', 15) AS CONTDESC
FROM DUAL
CONNECT BY LEVEL <= 100000;

COMMIT;




--2. CONT_DTL20 생성

DROP TABLE CONT_DTL20;

CREATE TABLE CONT_DTL20
(
    CONTDTLID  VARCHAR2(5),
    PRODCODE  VARCHAR2(10),
    USERCODE  VARCHAR2(10),
    DTLDATE VARCHAR2(8),
    DTLQTY NUMBER,
    DTLPRICE NUMBER,
    DTLDESC VARCHAR2(300)
)
;

ALTER TABLE CONT_DTL20 NOLOGGING;

---------------
--100000까지 숫자 중 5의 배수를 10개 씩 출력하라.
INSERT /*+ APPEND*/ INTO CONT_DTL20
SELECT  'D' || ROUND(DBMS_RANDOM.VALUE(1, 3000),0) AS CONTDTLID,
        LVL AS PRODCODE,
        NULL AS USERCODE,
        '2016'||LPAD(ROUND(DBMS_RANDOM.VALUE(1, 3),0), 2,0)||LPAD(ROUND(DBMS_RANDOM.VALUE(1, 28),0), 2,0) AS DTLDATE,
        ROUND(DBMS_RANDOM.VALUE(1, 10),0) AS DTLQTY,
        ROUND(DBMS_RANDOM.VALUE(1000, 10000),-2) AS DTLPRICE,
        DBMS_RANDOM.STRING('A', 15) AS DTLDESC
FROM (SELECT LEVEL LVL FROM DUAL CONNECT BY LEVEL <= 100000), (SELECT LEVEL FROM DUAL CONNECT BY LEVEL <=10) WHERE MOD(LVL,5) = 0
UNION ALL
--100000까지 숫자 중 5의 배수 제외한 8, 11의 배수를 50개 씩 출력하라.
SELECT  'D' || ROUND(DBMS_RANDOM.VALUE(1, 3000),0) AS CONTDTLID,
        NULL AS PRODCODE,
        LVL AS USERCODE,
        '2016'||LPAD(ROUND(DBMS_RANDOM.VALUE(1, 3),0), 2,0)||LPAD(ROUND(DBMS_RANDOM.VALUE(1, 28),0), 2,0) AS DTLDATE,
        ROUND(DBMS_RANDOM.VALUE(1, 10),0) AS DTLQTY,
        ROUND(DBMS_RANDOM.VALUE(1000, 10000),-2) AS DTLPRICE,
        DBMS_RANDOM.STRING('A', 15) AS DTLDESC
FROM (SELECT LEVEL LVL FROM DUAL CONNECT BY LEVEL <= 100000), (SELECT LEVEL FROM DUAL CONNECT BY LEVEL <=50) WHERE (MOD(LVL,8) = 0 OR MOD(LVL, 11) = 0) AND MOD(LVL, 5) NOT IN (0)
ORDER BY DBMS_RANDOM.RANDOM ;
-------------



COMMIT;


SELECT * FROM CONT20;

SELECT * FROM CONT_DTL20;

SELECT COUNT(*) FROM CONT20;

SELECT COUNT(*) FROM CONT_DTL20;




--원본 SQL
SELECT /*+ FULL(C) FULL(D) */ *
FROM CONT20 C, CONT_DTL20 D
WHERE C.CONTCODE = D.PRODCODE
AND SUBSTR(C.CONTDATE,1,6) = SUBSTR(D.DTLDATE,1,6)
AND D.CONTDTLID = 'D3000'
AND D.PRODCODE IS NOT NULL
AND C.PCODE IN ('A', 'B', 'C', 'D', 'E', 'F')
UNION ALL
SELECT /*+ FULL(C) FULL(D) */ *
FROM CONT20 C, CONT_DTL20 D
WHERE C.CONTCODE = D.USERCODE
AND SUBSTR(C.CONTDATE,1,6) = SUBSTR(D.DTLDATE,1,6)
AND D.CONTDTLID = 'D3000'
AND D.PRODCODE IS NULL
AND C.PCODE IN ('A', 'B', 'C', 'D', 'E', 'F')
;


--튜닝 SQL
--인덱스 미고려
SELECT /*+ FULL(C) FULL(D) */*
FROM CONT20 C, CONT_DTL20 D
WHERE C.CONTCODE = CASE WHEN D.PRODCODE IS NOT NULL THEN D.PRODCODE
                   WHEN D.PRODCODE IS NULL THEN D.USERCODE END
AND SUBSTR(C.CONTDATE,1,6) = SUBSTR(D.DTLDATE,1,6)
AND D.CONTDTLID = 'D3000'
AND C.PCODE IN ('A', 'B', 'C', 'D', 'E', 'F')
;

