-- http://blog.naver.com/oracledo/220564130933

CREATE TABLE TB_CUST
(
  CUST_NO VARCHAR2(10),
  CUST_NM VARCHAR2(50),
  JUMIN_NO CHAR(13),
  CONSTRAINT TB_CUST_PK PRIMARY KEY(CUST_NO)
);
-- 100만건
-- name, jumin은 선택 (입력할려면 둘 다 입력))

CREATE TABLE TB_CONT
(
  CONT_NO CHAR(10),
  CONT_DT DATE,
  TERMI_DT DATE,
  TERMI_AMT NUMBER,
  CUST_NO VARCHAR2(10),
  CONSTRAINT TB_CONT_PK PRIMARY KEY(CONT_NO)
);

-- 하루편균 1천건(총 1천만건)) (DATE는 필수 검색기간은 1주일 제한)

TB_CUST_01 (CUST_NM, JUMIN_NO)
TB_CONT_01 (CUST_NO, CONT_DT)
TB_CONT_02 (CONT_DT, CUST_NO)


SELECT /*+ LEADING(C) USE_NL(T) INDEX(C TB_CUST_01) INDEX(T TB_CONT_01) */
       C.CUST_NO, C.CUST_NM, C.JUMIN_NO, T.CONT_NO, T.CONT_DT, T.TERMI_DT, T.TERMI_AMT
  FROM TB_CUST C, TB_CONT T
 WHERE C.CUST_NO = T.CUST_NO
   AND T.CONT_DT BETWEEN TO_DATE(:FROM_DATE, 'yyyymmdd')
                     AND TO_DATE(:TO_DATE + '235959', 'yyyymmddhh24miss')
   AND (:JUMIN IS NOT NULL AND :NAME IS NOT NULL)
   AND C.CUST_NM = :NAME
   AND C.JUMIN_NO LIKE :JUMIN || '%'

UNION ALL

SELECT /*+ LEADING(T) USE_NL(C)  INDEX(C TB_CUST_PK) INDEX(T TB_CONT_02) */
       C.CUST_NO, C.CUST_NM, C.JUMIN_NO, T.CONT_NO, T.CONT_DT, T.TERMI_DT, T.TERMI_AMT
  FROM TB_CUST C, TB_CONT T
 WHERE C.CUST_NO = T.CUST_NO
   AND T.CONT_DT BETWEEN TO_DATE(:FROM_DATE, 'yyyymmdd')
                     AND TO_DATE(:TO_DATE + '235959', 'yyyymmddhh24miss')
   AND (:JUMIN IS NULL OR :NAME IS NULL)
